-- AI Productivity Hub - Database Schema Evolution v2

-- 1. Extend users table to support email and verification status
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email TEXT UNIQUE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE;

-- 2. User configurations for persistence (To remember model settings)
CREATE TABLE IF NOT EXISTS public.user_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    model_name TEXT NOT NULL,
    api_key_encrypted TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id)
);

-- 3. Verification codes for email/password recovery
CREATE TABLE IF NOT EXISTS public.verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    email TEXT,
    code TEXT NOT NULL,
    type TEXT NOT NULL, -- 'register', 'reset_password', 'bind_email'
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for user_configs (User can only read/write their own config)
ALTER TABLE public.user_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only access their own config" 
ON public.user_configs 
FOR ALL 
TO authenticated 
USING (auth.uid() = user_id);

-- Update existing logs table to ensure user association
-- ALTER TABLE public.logs ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES public.users(id);

-- Add index for fast log searching
CREATE INDEX IF NOT EXISTS idx_logs_content_trgm ON public.logs USING gin (content gin_trgm_ops);
-- Note: Requires pg_trgm extension if not already enabled:
-- CREATE EXTENSION IF NOT EXISTS pg_trgm;
