-- AI Productivity Hub - Database Schema Evolution v5 (Reports Archive Support)

-- 1. Create reports table to archive weekly/custom summaries
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content JSONB NOT NULL, -- Store structured report (executiveSummary, nextWeekSuggestions, etc.)
    start_date DATE, -- Optional: period start
    end_date DATE,   -- Optional: period end
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add indices for performance
CREATE INDEX IF NOT EXISTS idx_reports_user_id ON public.reports(user_id);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON public.reports(created_at DESC);

-- 3. Comment for documentation
COMMENT ON TABLE public.reports IS '用于存储用户生成的结构化周报或周期性总结快照';
COMMENT ON COLUMN public.reports.content IS '存储 AI 生成的 JSON 格式报告，包含摘要、建议、以及当时生成的原始统计数据快照';
