-- Create users table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    phone TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- enable RLS (optional but recommended)
-- ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Create logs table if not exists (assuming it was missing based on error log)
CREATE TABLE IF NOT EXISTS public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT,
    tags TEXT[],
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id BIGINT REFERENCES public.users(id) -- if we want to associate logs with users later
);
