-- AI Productivity Hub - Database Schema Evolution v2

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1. Extend users table to support email and verification status
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email TEXT UNIQUE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS github_id TEXT UNIQUE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- 2. User configurations for persistence (To remember model settings)
CREATE TABLE IF NOT EXISTS public.user_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    model_name TEXT NOT NULL,
    api_key_encrypted TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id)
);

-- 3. Verification codes for email/password recovery
CREATE TABLE IF NOT EXISTS public.verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    email TEXT,
    code TEXT NOT NULL,
    type TEXT NOT NULL, -- 'register', 'reset_password', 'bind_email'
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: RLS is disabled by default for user_configs in this project
-- because we use a custom backend login system (BIGINT IDs) 
-- that does not map directly to Supabase Auth's UUID.
-- Privacy is enforced at the application layer in main.py.
-- ALTER TABLE public.user_configs ENABLE ROW LEVEL SECURITY;

-- Add index for fast log searching
CREATE INDEX IF NOT EXISTS idx_logs_content_trgm ON public.logs USING gin (content gin_trgm_ops);
